# PYTHON ASSIGNMENT:
                                                                                             PREPARED BY IRFAN ALI ROLL NO: 2K22/CSE/48
##  Perform numpy functions on Types of matrix
### Common NumPy Array Functions

* There are many NumPy array functions available but here are some of the most commonly used ones.

* Array Operations	Functions
* Array Creation Functions	    np.array(), np.zeros(), np.ones(), np.empty(), etc.
* Array Manipulation Functions	np.reshape(), np.transpose(), etc.
* Array Mathematical Functions	np.add(), np.subtract(), np.sqrt(), np.power(), etc.
* Array Statistical Functions	np.median(), np.mean(), np.std(), and np.var().


# Matrix and its types

## What is matrix?

* A set of numbers arranged in rows and columns so as to form a rectangular array. The numbers are called the elements, or entries, of the matrix.
* If there are m rows and n columns, the matrix is said to be an “m by n” matrix, written “m × n.”
* There are many types of matrices depending on the elements in the matrix, order, and certain sets of conditions. The different types of matrices are mentioned below:

# 1) Singleton Matrix

* A matrix that has only one element is called a singleton matrix. 
* In this type of matrix number of columns and the number of rows is equal to 1

In [1]:
import numpy as np

singleton_matrix = np.array([[1]])
print("Singleton Matrix:")
print(singleton_matrix)

Singleton Matrix:
[[1]]


# 2) Row Matrix
* a row matrix is a type of matrix that has a single row. But the number of columns could be more than one.

In [2]:
row_matrix = np.array([[1, 2, 3]])
print("Row Matrix:")
print(row_matrix)

Row Matrix:
[[1 2 3]]


# 3) Column Matrix
* A column matrix is a type of matrix that has only one column. The order of the column matrix is represented by m x 1.

In [3]:
column_matrix = np.array([[1], [2], [3]])
print("Column Matrix:")
print(column_matrix)

Column Matrix:
[[1]
 [2]
 [3]]


# 4) Square Matrix
* 
A square matrix is a matrix with the same number of rows and columns
*    An n-by-n matrix is known as a square matrix of order n
*  . Any two squar   matrices of the same order can be added and multipliedix

In [4]:
square_matrix = np.array([[1, 2], [3, 4]])
print("Square Matrix:")
print(square_matrix)

Square Matrix:
[[1 2]
 [3 4]]


# 5) Identity Matrix
* In which all the elements on the main diagonal are equal to 1 and all other elements are equal to O.
* The identity matrix In of size n is the n-by-n matrix.


In [5]:
def identity(n):
    return np.eye(n)
n = 2
identity_matrix = identity(n)
print("Identity Matrix:")
print(identity_matrix)


Identity Matrix:
[[1. 0.]
 [0. 1.]]


# 6) Null or Zero matrix
* A matrix whose all elements are zero is called a Null Matrix. A null matrix is also called a Zero Matrix because its all elements are zero. 

In [6]:
zeros_matrix=np.zeros([2,3])
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


# 7) Matrix of ones 
* A matrix of ones or all-ones matrix is a matrix where every entry is equal to one.

In [7]:
matrix_of_ones=np.ones([2,3])
print(matrix_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


# 8) Horizontal Matrix
* A matrix in which the number of rows is lower than the number of columns is called a Horizontal Matrix

In [8]:
horizontal_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Horizontal Matrix:")
print(horizontal_matrix)


Horizontal Matrix:
[[1 2 3]
 [4 5 6]]


# 9) Vertical Matrix
* The matrix in which the number of rows greater than the number of columns is called a Vertical Matrix

In [9]:
vertical_matrix = np.array([[1], [2], [3]])
print("Vertical Matrix:")
print(vertical_matrix)

Vertical Matrix:
[[1]
 [2]
 [3]]


# 10)Rectangular Matrix
* A matrix that does not have an equal number of rows and columns is known as a Rectangular Matrix.

In [10]:
rectangular_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Rectangular Matrix:")
print(rectangular_matrix)


Rectangular Matrix:
[[1 2 3]
 [4 5 6]]


# 1D and 2D random Matrix
* np.random.randint() is one of the function for doing random sampling in numpy.
* It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive)

In [11]:
random_function = np.random.randint(1, 5, size=(4, 4))
print(random_function)

[[3 2 1 1]
 [4 1 4 4]
 [4 4 1 3]
 [3 2 4 1]]



# THANK YOU VERY MUCH